export const POKEMON_ACTION_START = "POKEMON_ACTION_START";
export const POKEMON_ACTION_FAIL = "POKEMON_ACTION_FAIL";
export const ALL_POKEMON_FETCH_SUCCESS = "ALL_POKEMON_FETCH_SUCCESS";
export const POKEMON_FETCH_SUCCESS = "POKEMON_FETCH_SUCCESS";
export const CHANGE_CATCHED_POKEMON = "CHANGE_CATCHED_POKEMON";
